---
title: "Final Project"
author: "Tom Linsenmeyer"
date: "2024-11-05"
output: word_document
---

```{r message=FALSE}
library(tidyverse)
```

```{r}
hops<- read.csv('HopsData.csv')
weather <- read.csv('WeatherData.csv')
hops 

```

```{r}

data <- data.frame(
    YEAR =weather$DATE,
    AVG_TEMP = weather$TAVG,
    MIN_TEMP = weather$TMIN,
    MAX_TEMP = weather$TMAX, 
    PRECIP = weather$PRCP,
    LBS_HOPS = hops$Value)
 
data

```

```{r}
temp_weight_plot <- ggplot() +
  
  geom_line(data= data, mapping= aes(YEAR, LBS_HOPS/1000000), color= 'green') +
  geom_line(data= data, mapping= aes(YEAR, AVG_TEMP), color= "blue") +
  xlab("YEAR")+ ylab("Hops Produced in Mlbs(Green), Average Temperature(Blue)")

temp_weight_plot
```

```{r}
precip_weight_plot <- ggplot() +
  
  geom_line(data= data, mapping= aes(YEAR, LBS_HOPS/10000000), color= 'green') +
  geom_line(data= data, mapping= aes(YEAR, PRECIP), color= "blue") +
  xlab("YEAR")+ 
  ylab("Hops Produced in Mlbs(Green), Total Precipitation(Blue)") 
  

precip_weight_plot
```

```{r}
temp_precip_plot <- ggplot() +
  
  geom_line(data= data, mapping= aes(YEAR, AVG_TEMP), color= 'blue') +
  geom_line(data= data, mapping= aes(YEAR, PRECIP), color= "green") +
  xlab("YEAR")+ 
  ylab("Precipitation(Green), Average Temperatue(Blue)") 
  

temp_precip_plot
```

